services:
  frontend:
    image:
    ports: "443:8043"
    networks:
      - frontend-network
    configs: 
      - httpd-config
    secrets:
      - server-certificate
  backend:
    image:
    volumes:
    - db-data:/etc/data
    networks:
      - backend-network

  volumes:
  db-data:
  driver: local
  driver_opts:
    type: none
    device: /path/to/local/data
    o: bind
    size: "10GiB"
  configs:
  httpd-config:
    external: true
  secrets:
    server-certificate:
      external: true 
networks:
  frontend-network: {}
  backend-network: {}