services:
  agent:
    build: ./agent
    container_name: novisec-agent
    environment:
      - AGENT_ID=novisec-agent-001
      - API_URL=http://api:3001
      - API_TOKEN=agent-dev-token
      - TRIVY_ENABLED=true
      - SCAN_TYPE=MANUAL_GLOBAL
    volumes:
      # Accès au socket Docker en lecture seule selon le CDC (4.2)
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - api
    networks:
      - novisec-net

  api:
    build: ./api
    container_name: novisec-api
    ports:
      - "3000:3001"
      - "3002:3002"
    environment:
      - PORT=3001
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=novisec
      - POSTGRES_PASSWORD=novisec_secure_pass
      - POSTGRES_DB=novisec_db
      - ADMIN_TOKEN=admin-dev-token
      - VIEWER_TOKEN=viewer-dev-token
      - AGENT_TOKEN=agent-dev-token
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin-pass
      - VIEWER_USER=viewer
      - VIEWER_PASSWORD=viewer-pass
      - AGENT_USER=agent
      - AGENT_PASSWORD=agent-pass
      - AUTH_JWT_SECRET=change-me-in-prod
      - AUTH_JWT_EXPIRES_IN=8h
      - HTTPS_ENABLED=true
      - HTTPS_KEY_FILE=/certs/server.key
      - HTTPS_CERT_FILE=/certs/server.crt
    depends_on:
      - db
    networks:
      - novisec-net
    volumes:
      - ./certs:/certs:ro

  frontend:
    build: ./web
    container_name: novisec-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    networks:
      - novisec-net

  db:
    image: postgres:16-alpine # PostgreSQL selon le CDC (4.1)
    container_name: novisec-db
    environment:
      - POSTGRES_USER=novisec
      - POSTGRES_PASSWORD=novisec_secure_pass
      - POSTGRES_DB=novisec_db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/schema:/docker-entrypoint-initdb.d:ro
    networks:
      - novisec-net
    ports:
      - "5432:5432"

  cve-updater:
    image: aquasec/trivy:0.44.1
    container_name: novisec-cve-updater
    restart: unless-stopped
    networks:
      - novisec-net
    command: sh -c "while true; do trivy db update || true; sleep 21600; done"

volumes:
  db-data:

networks:
  novisec-net:
    driver: bridge
